exclude: '^docs/conf.py'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=lf']  # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows

## If you want to avoid flake8 errors due to unused vars or imports:
# - repo: https://github.com/myint/autoflake
#   rev: v1.4
#   hooks:
#   - id: autoflake
#     args: [
#       --in-place,
#       --remove-all-unused-imports,
#       --remove-unused-variables,
#     ]

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort

#- repo: https://github.com/psf/black
#  rev: 22.6.0
#  hooks:
#  - id: black
#    language_version: python3

## If like to embrace black styles even in the docs:
# - repo: https://github.com/asottile/blacken-docs
#   rev: v1.12.0
#   hooks:
#   - id: blacken-docs
#     additional_dependencies: [black]

- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
  ## You can add flake8 plugins via `additional_dependencies`:
  #  additional_dependencies: [flake8-bugbear]

- repo: local
  hooks:
    - id: no_debug_comments
      name: No Debug Comments
      language: pygrep
      entry: '(^[ \t]*#DEBUG|  #DEBUG[A-Z_]*$)'
      types:
        - file
      fail_fast: true
    - id: no_fixme_comments
      name: No Fixme Comments
      language: pygrep
      entry: '#FIXME'
      types:
        - file
      exclude: .pre-commit-config.yaml
      fail_fast: true
    - id: no_testing_comments
      name: No Testing Comments
      language: pygrep
      entry: '#[A-Z0-9_]*TEST'
      types:
        - file
      exclude: '(^.pre-commit-config.yaml|^tests/docker/run.sh)'
      fail_fast: true
